language: node_js
node_js:
  - 8
  - 10
  - stable
dist: xenial
sudo: required
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  # install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
script:
  - yarn lint
